/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void testRollMethod() {
        // Create an instance of DiceRoller class
        Library diceRoller = new Library();
        // Test case 1: Roll the dice once
        int n1 = 1;
        int[] rolls1 = diceRoller.roll(n1);
        assertEquals(n1, rolls1.length, "Expected length of rolls1 array to be " + n1);
        // Test case 2: Roll the dice multiple times
        int n2 = 5;
        int[] rolls2 = diceRoller.roll(n2);
        assertEquals(n2, rolls2.length, "Expected length of rolls2 array to be " + n2);
        // Test case 3: Roll the dice zero times
        int n3 = 0;
        int[] rolls3 = diceRoller.roll(n3);
        assertEquals(n3, rolls3.length, "Expected length of rolls3 array to be " + n3);
    }
}
