/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void myRestaurant(){
        //arrange
        Restaurant dennys = new Restaurant("Denny's", 4, 2);
        String restName = "This restaurant is so amazing: Denny's";
        // act
        String actualOutput = dennys.restaurantName();
        // assert
        assertEquals(restName, actualOutput);
    }

    @Test void theReviews(){
        //arrange
        Review theReviews = new Review("Amazing!", "BoPeep", 4);
        String bestReview = "The reviews are: Author: BoPeep Stars: 4 Body: Amazing!";

        // act
        String actualOutput = theReviews.theReviews();

        // assert
        assertEquals(bestReview, actualOutput);
    }

    @Test void theShop(){
        //arrange
        Shop theShop = new Shop("NickKnacks","Best ever!", 2 );
        String shopify = theShop.toString();
        //act
        String actualOutput = theShop.toString();
        //assert
        assertEquals(shopify, actualOutput);
    }

}
